<h1 style="color:aqua; text-align:center;">NumPy</h1>

<h3 style="color:white">0. Importing and Verifying</h3>

In [1]:
import numpy as np ;
print(np.__version__)

2.0.2


In [2]:
import platform, os

print("OS System:", platform.system())
print("Is Google Colab:", 'google.colab' in str(get_ipython()))
print("Working Directory:", os.getcwd())

OS System: Linux
Is Google Colab: True
Working Directory: /content


<h3 style="color:white;">1. Basic Array Creation</h3>

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array([1, 2, 3, "Hello"])
arr

array(['1', '2', '3', 'Hello'], dtype='<U21')

In [5]:
# Creating 2D array
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h3 style="color:white;">2. Array Generation Functions</h3>

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [11]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [12]:
np.linspace(10, 20, 5, dtype=int)

array([10, 12, 15, 17, 20])

<h3 style="color:white;">3. Random Generation Functions</h3>

In [13]:
# Generate random number between 0 and 1
np.random.rand(5)

array([0.4882773 , 0.64286119, 0.359099  , 0.04820198, 0.58487855])

In [14]:
# Generate random numbers between -3 and 3
np.random.randn(10)

array([ 0.45426528,  0.72817339, -2.05757303,  1.53748622,  0.06276991,
        0.31294911,  0.69708281,  0.51851975, -0.52655792,  0.36883183])

In [15]:
np.random.randint(10, 20, 10)

array([19, 12, 17, 14, 19, 19, 18, 18, 17, 17])

In [16]:
np.random.randint(1, 20, 5)

array([15,  3,  4, 16,  1])

<h3 style="color:white;">4. Array Attributes</h3>

In [17]:
arr = np.arange(20)
arr = arr.reshape((4,5))

In [18]:
arr.shape

(4, 5)

In [19]:
arr.size

20

In [20]:
arr.dtype

dtype('int64')

<h3 style="color:white;">5. Array Methods</h3>

In [21]:
arr = np.arange(10, 30).reshape(4, 5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [22]:
arr.min()

np.int64(10)

In [23]:
print(arr.max())

29


In [24]:
print(arr.argmax())

19


In [25]:
arr.sum()

np.int64(390)

In [26]:
arr.sum(axis=1)

array([ 60,  85, 110, 135])

In [27]:
np.argmax(arr, axis=0)

array([3, 3, 3, 3, 3])

<h3 style="color:white;">6. Indexing and Slicing of Matrices</h3>

In [32]:
arr = np.arange(10, 30).reshape((4, 5))
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [33]:
arr[0]

array([10, 11, 12, 13, 14])

In [37]:
print(arr[0,0])

10


In [36]:
print(arr[0][0])

10


In [38]:
slice = arr[1:, 1:3]
slice

array([[16, 17],
       [21, 22],
       [26, 27]])

In [39]:
a = arr
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [40]:
a[0,0] = 110
a

array([[110,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [41]:
arr

array([[110,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [42]:
a = np.copy(arr)
a

array([[110,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [43]:
a[0,0] = 234
a

array([[234,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [44]:
arr

array([[110,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [46]:
# Selecting a column
print(arr[:, 2])

[12 17 22 27]


<h3 style="color:white;">7. Boolean Indexing</h3>

In [52]:
arr = np.arange(10, 50).reshape((4, 10))
arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
bool_idx = arr%2 == 0
bool_idx

array([[ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])

In [54]:
print(arr[bool_idx])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
